version: '3.8'

services:
  linjing:
    # 主服务配置保持不变
    depends_on:
      - postgres
      - redis
      - rabbitmq

  # 数据库服务
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: linjing
      POSTGRES_DB: linjing_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linjing"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 缓存服务
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s

  # 消息队列
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"  # 管理界面
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s

  # 监控服务
  prometheus:
    image: prom/prometheus:v2.47
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - linjing

  grafana:
    image: grafana/grafana-oss:10.2-alpine
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  grafana_data:

networks:
  linjing-net:
    driver: bridge
