version: '3.8'

services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: unless-stopped
    networks:
      - linjing-net
    ports:
      - "3100:3000"
      - "3101:3001"
      - "6099:6099"
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - TZ=${TZ:-Asia/Shanghai}
    volumes:
      - /app/qq:/app/.config/QQ
      - /app/napcat/config:/app/napcat/config 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  linjing:
    build: 
      context: .
      dockerfile: Dockerfile
    image: linjing-bot:latest
    restart: unless-stopped
    depends_on:
      napcat:
        condition: service_healthy
    networks:
      - linjing-net
    env_file:
      - ./envexample
    environment:
      - ONEBOT_HOST=napcat
      - ONEBOT_PORT=6099
      - ONEBOT_PROTOCOL=v11
      - ONEBOT_ACCESS_TOKEN=linjing-napcat-token-123456
    volumes:
      - /app/linjing/MaiBot-:/app:rw
      - linjing-data:/app/data:rw
      - linjing-logs:/app/logs:rw
    ports:
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - linjing-net
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=false

networks:
  linjing-net:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  linjing-data:
  linjing-logs:
