version: '3.8'

services:
  napcat:
    image: napcat/napcat:latest
    restart: unless-stopped
    networks:
      - linjing-net
    ports:
      - "6700:6700"
      - "5700:5700"
    volumes:
      - ./config/napcat:/config
    env_file:
      - ./.env
    environment:
      - TZ=${TZ}
    security_opt:
      - no-new-privileges:true
    read_only: true

  linjing:
    build: 
      context: .
      dockerfile: Dockerfile
    image: linjing-bot:latest
    restart: unless-stopped
    depends_on:
      napcat:
        condition: service_healthy
    networks:
      - linjing-net
    env_file:
      - ./.env
    environment:
      - LINJING_ENV=production
      - PYTHONPATH=/app/linjing
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./linjing:/app/linjing
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

networks:
  linjing-net:
    driver: bridge
    internal: true

volumes:
  linjing-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
