version: '3.8'

services:
  linjing:
    image: python:3.10-slim
    restart: unless-stopped
    working_dir: /linjing
    volumes:
      - ./linjing:/linjing
      - linjing_data:/linjing/storage
      - linjing_logs:/linjing/logs
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      - DATA_PATH=/linjing/storage
      - LOG_PATH=/linjing/logs
    ports:
      - "8000:8000"
    networks:
      - linjing-net
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - linjing-net
    ports:
      - "6333:6333"
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true

volumes:
  linjing_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage
  linjing_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  qdrant_data:
    name: linjing_qdrant_data

networks:
  linjing-net:
    driver: bridge
