# napcat配置
server:
  host: 0.0.0.0
  port: 6099
  access_token: "linjing-napcat-token-123456"
  
onebot:
  http:
    enabled: true
    host: 0.0.0.0
    port: 3000
  ws:
    enabled: true
    host: 0.0.0.0
    port: 3001
