version: '3.8'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:5.0
    container_name: maibot-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-maibot}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-maibotsecret}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - maibot-network

  # Redis 缓存服务
  redis:
    image: redis:7.0-alpine
    container_name: maibot-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - maibot-network

  # MaiBot 主服务
  maibot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: maibot-app
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "${MAIBOT_HTTP_PORT:-8081}:8081"
      - "${MAIBOT_WS_PORT:-8080}:8080"
    environment:
      # 数据库配置
      MONGODB_URI: mongodb://${MONGO_USER:-maibot}:${MONGO_PASSWORD:-maibotsecret}@mongodb:27017/
      REDIS_URI: redis://redis:6379/0
      
      # 服务器配置
      SERVER_HOST: 0.0.0.0
      HTTP_PORT: 8081
      WS_PORT: 8080
      
      # napcat配置
      NAPCAT_API_BASE: ${NAPCAT_API_BASE:-http://napcat:3000}
      NAPCAT_AUTH_TOKEN: ${NAPCAT_AUTH_TOKEN:-}
      
      # LLM配置
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      
      # 调试模式
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ../config:/app/config
      - ../logs:/app/logs
      - ../data:/app/data
    networks:
      - maibot-network
      
  # napcat服务
  napcat:
    image: napcat/napcat:latest  # 假设napcat有官方Docker镜像
    container_name: napcat
    restart: always
    ports:
      - "${NAPCAT_PORT:-3000}:3000"
    environment:
      # 这里添加napcat所需的环境变量
      # 具体值需要参考napcat文档
      NAPCAT_CONFIG: ${NAPCAT_CONFIG:-/data/config.yml}
    volumes:
      - napcat_data:/data
    networks:
      - maibot-network

volumes:
  mongodb_data:
  redis_data:
  napcat_data:

networks:
  maibot-network:
    driver: bridge 