# docker-compose.yml - 灵境机器人部署配置

services:
  # 主应用服务 - 灵境机器人
  linjing-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: linjing-bot:latest
    container_name: linjing-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # 使用当前目录的配置文件
      - linjing_data:/app/data             # 数据持久化
      - linjing_logs:/app/logs             # 日志持久化
    env_file:
      - ./.env                             # 使用当前目录的环境变量文件
    environment:
      - LINJING_ENV=production
      - LINJING_DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant                             # 移除健康检查依赖
    networks:
      - linjing_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # 向量数据库 - Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: linjing-qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - linjing_network
    ports:
      - "6333:6333"                        # 暴露端口便于调试
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true

# 自定义网络
networks:
  linjing_network:
    driver: bridge

# 数据卷定义
volumes:
  linjing_data:
    name: linjing_data
  linjing_logs:
    name: linjing_logs
  qdrant_data:
    name: linjing_qdrant_data